/**
 * AuthService API
 * Сервис авторизации пользователей
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.feature.auth.client.apis

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import org.astu.infrastructure.gateway.models.Tokens
import org.astu.infrastructure.DependencyInjection.GlobalDIContext

class YandexApi(private val basePath: String = "/") {
    private val client by GlobalDIContext.inject<HttpClient>()

    /**
     *
     * Авторизация через yandex аккаунт
     * @return Tokens
     */
    suspend fun yandexLoginGet(): Tokens {
        val response = client.get("${basePath}yandex/login") {}
        println(response)
        println()
        println(response.bodyAsText())
        return when (response.status) {
            HttpStatusCode.OK -> {
                response.body<Tokens>()
            }
            HttpStatusCode.Found -> {
                return Tokens("", "2")
            }
            else -> {
                throw RuntimeException()
            }
        }
    }

    /**
     *
     * Привязка пользователя с Yandex OAuth2
     * @return Tokens
     */
    suspend fun yandexRegistrationGet(tokens: Tokens): Tokens {
        val response = client.get("${basePath}yandex/registration") {
            this.header(HttpHeaders.Authorization, tokens.accessToken)
        }
        return when (response.status) {
            HttpStatusCode.OK -> response.body<Tokens>()
            else -> throw RuntimeException()
        }
    }
}
