@startuml
'https://plantuml.com/class-diagram

left to right direction

interface DefaultModifierProvider {
    getDefaultModifier(): Modifier
}
interface ContentProvider {
    @Composable Content(modifier: Modifier)
}

enum AttachmentType {
    FILE
    SURVEY
}

abstract class AttachmentContentBase {
    type: AttachmentType
}
ContentProvider <|.. AttachmentContentBase
DefaultModifierProvider <|.. AttachmentContentBase
AttachmentContentBase *-right- AttachmentType


'''''''''''''''''''''''''''''''' ФАЙЛЫ
rectangle Files {
    abstract class FileContentBase {
        name: String
        size: String
    }
    AttachmentContentBase <|-- FileContentBase

    class CurrentlyAttachedFileContent extends FileContentBase { }

    enum FileDownloadStata {
        NOT_DOWNLOADED
        DOWNLOADING
        DOWNLOADED
    }

    class AttachedFileContent extends FileContentBase {
        id: Uuid
        downloadState: FileDownloadStata
    }
    AttachedFileContent *-down- FileDownloadStata

    class AttachedDetachableFileContent extends FileContentBase {
        id: Uuid
        {field} }onDetachRequest: () -> Unit)
    }
}

'''''''''''''''''''''''''''''''' ОПРОСЫ
rectangle Surveys {
    ''''''''''''' Варианты ответов
    abstract class AnswerContentBase{
            id: Uuid
        text: String
    }
    ContentProvider <|.. AnswerContentBase
    DefaultModifierProvider <|.. AnswerContentBase
    abstract class UnvotedAnswerContentBase extends AnswerContentBase {
        canVote: MutableState<Boolean>
        isSelected(): Boolean
    }
    class MultipleChoiceAnswerContent extends UnvotedAnswerContentBase {
        selected: MutableState<Boolean>
    }
    class SingleChoiceAnswerContent extends UnvotedAnswerContentBase {
    }

    abstract class VotedAnswerContentBase extends AnswerContentBase {
        voterPercent: Int
    }
    class VotedAnswerContentSummary extends VotedAnswerContentBase {

    }
    class VotedAnswerContentDetails extends VotedAnswerContentBase {
        votersRootNode: INode
    }

    ''''''''''''' Вопросы
    abstract class QuestionContentBase {
        id: Uuid
        text: String
        answers: List<AnswerContentBase>
    }
    ContentProvider <|.. QuestionContentBase
    DefaultModifierProvider <|.. QuestionContentBase
    AnswerContentBase *-right- QuestionContentBase

    abstract class UnvotedQuestionContentBase extends QuestionContentBase {
    }
    class MultipleChoiceQuestionContent extends UnvotedQuestionContentBase {
    }
    class SingleChoiceQuestionContent extends UnvotedQuestionContentBase {
    }
    class VotedQuestionContent extends QuestionContentBase {
    }


    ''''''''''''' Опросы
    abstract class SurveyContentBase {
        id: Uuid
        questions: List<QuestionContentBase>
    }
    AttachmentContentBase <|-- SurveyContentBase
    QuestionContentBase *-- SurveyContentBase

    class AttachedSurveyContent extends SurveyContentBase {
    }
}

@enduml