/**
 * gateway API
 * gateway API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.feature.single_window.client.models

import kotlinx.serialization.Serializable

/**
 * 
 * @param templateId 
 * @param type 
 * @param email 
 * @param fields 
 */
@Serializable
data class AddRequestDTO (

    val templateId: String,
    val type: Type,
    val email: String? = null,
    val fields: List<AddRequirementFieldDTO>
) {
    /**
    * 
    * Values: FACETOFACE,EMAIL
    */
    enum class Type(val value: String){
        FACETOFACE("FACETOFACE"),
        EMAIL("EMAIL");
    }
}