/**
 * gateway API
 * gateway API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.infrastructure.gateway.models

import kotlinx.serialization.Serializable


/**
 * 
 * @param name 
 */
@Serializable
data class AddChatDTO (

    val name: String
)