/**
 * gateway API
 * gateway API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.infrastructure.gateway.models

import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

/**
 * 
 * @param id 
 * @param text 
 * @param userId 
 * @param utcDateTime 
 * @param attachment 
 */
@Serializable
data class MessageDTO (

    val id: String,
    val text: String,
    val userId: String,
    val utcDateTime: Instant,
    val attachment: List<String>
)