/**
 * AuthService API
 * Сервис авторизации пользователей
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.feature.auth.client.models

import kotlinx.serialization.Serializable

/**
 * @param login
 * @param password 
 */
@Serializable
data class JWTRegistrationDTO (
    val login: String,
    val password: String
)