/**
 * AuthService API
 * Сервис авторизации пользователей
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import kotlinx.serialization.Serializable


/**
 *
 * @param accessToken
 * @param refreshToken 
 */
@Serializable
data class Tokens (
    val accessToken: String,
    val refreshToken: String
)