/**
 * gateway API
 * gateway API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.feature.universal_request.client.models

import kotlinx.serialization.Serializable
import org.astu.infrastructure.JavaSerializable

/**
 * 
 */
@Serializable
data class TemplateFieldDTO (
    val name: String,
    val value: String
): JavaSerializable